name: Uptime Kuma
services:
    uptime-kuma:
        container_name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
            - 3001:3001
        volumes:
            - ./data:/app/data
        networks:
          - nginx_default
        restart: always

networks:
  nginx_default:
    name: nginx_default
    external: true
