services:
    server:
        container_name: vaultwarden
        volumes:
            - ./data:/data/
        ports:
            - '4935:80'
        labels:
            - "com.centurylinklabs.watchtower.monitor-only=true"
        image: 'vaultwarden/server:1.30.5'
        restart: unless-stopped

networks:
  default:
    name: nginx_default
    external: true
