services:
    synapse:
        image: "matrixdotorg/synapse:latest"
        container_name: "synapse-matrix"
        volumes:
            - "./data:/data"
        env_file:
          - .env
        environment:
            VIRTUAL_PORT: 8008
            SYNAPSE_SERVER_NAME: ${SERVER_NAME:?address required}
            SYNAPSE_REPORT_STATS: "no"
        networks:
          - matrix
          - nginx_default

    postgresql:
        image: postgres:latest
        restart: always
        env_file:
          - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASS:?db password required}
            POSTGRES_USER: synapse
            POSTGRES_DB: synapse
            POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
        volumes:
            - "./postgresdata/:/var/lib/postgresql/"
        networks:
          - matrix

networks:
  nginx_default:
    name: nginx_default
    external: true
  matrix:
