name: Portainer
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      volumes:
        - portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
volumes:
  portainer:
